name: Depex CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/ --cov=app --cov-report=term-missing

      - name: Run tests with Coverage
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          title: "🧪 Depex Test Report" 
          badge-title: "Coverage"
          hide-badge: false
          hide-report: false
          create-new-comment: false 

      - name: Build Docker image
        run: |
          docker build -t fastapi-task-management .

      - name: Make request to external service
        env:
          LOGIN_URL: https://tasimetric-willard-noncosmic.ngrok-free.dev/auth/login
          LOGIN_EMAIL: ${{ secrets.DEPEX_EMAIL }}
          LOGIN_PASSWORD: ${{ secrets.DEPEX_PASSWORD }}
        run: |
          RESPONSE=$(curl -sS -X POST "$LOGIN_URL" \
            -H "Content-Type: application/json" \
            -d "{\"email\":\"$LOGIN_EMAIL\", \"password\":\"$LOGIN_PASSWORD\"}")

          TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')

          if [ "$TOKEN" == "null" ] || [ -z "$TOKEN" ]; then
            echo "Error: Could not extract access token"
            exit 1
          fi

          echo "ACCESS_TOKEN=$TOKEN" >> $GITHUB_ENV