name: Depex CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/ --cov=app --cov-report=term-missing

      - name: Run tests with Coverage
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          title: "🧪 Depex Test Report" 
          badge-title: "Coverage"
          hide-badge: false
          hide-report: false
          create-new-comment: false 

      - name: Build Docker image
        run: |
          docker build -t fastapi-task-management .

      # - name: Make request to external service
      #   env:
      #     LOGIN_URL: https://tasimetric-willard-noncosmic.ngrok-free.dev/auth/login
      #     LOGIN_EMAIL: ${{ secrets.DEPEX_EMAIL }}
      #     LOGIN_PASSWORD: ${{ secrets.DEPEX_PASSWORD }}
      #   run: |
      #     RESPONSE=$(curl -sS -X POST "$LOGIN_URL" \
      #       -H "Content-Type: application/json" \
      #       -d "{\"email\":\"$LOGIN_EMAIL\", \"password\":\"$LOGIN_PASSWORD\"}")

      #     TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')

      #     if [ "$TOKEN" == "null" ] || [ -z "$TOKEN" ]; then
      #       echo "Error: Could not extract access token"
      #       exit 1
      #     fi

      #     echo "ACCESS_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Check API and Generate Report
        id: api_check
        env:
          LOGIN_URL: https://tasimetric-willard-noncosmic.ngrok-free.dev/auth/login
          LOGIN_EMAIL: ${{ secrets.DEPEX_EMAIL }}
          LOGIN_PASSWORD: ${{ secrets.DEPEX_PASSWORD }}
        run: |
          response=$(curl -s -w "\n%{http_code}" -X POST "$LOGIN_URL" \
            -H "Content-Type: application/json" \
            -d "{\"email\":\"$LOGIN_EMAIL\", \"password\":\"$LOGIN_PASSWORD\"}")

          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)

          TOKEN=$(echo "$body" | jq -r '.access_token')
          USER_ID=$(echo "$body" | jq -r '.user_id')

          if [ "$TOKEN" == "null" ] || [ -z "$TOKEN" ]; then
            echo "Error: Could not extract access token"
            exit 1
          fi

          echo "ACCESS_TOKEN=$TOKEN" >> $GITHUB_ENV
          echo "USER_ID=$USER_ID" >> $GITHUB_ENV

          if [ "$http_code" == "200" ]; then
            status_icon="🟢"
            status_msg="Success"
            color="good"
          else
            status_icon="🔴"
            status_msg="Failed"
            color="danger"
          fi
          
          echo "## 🔐 Authentication Service Report" > api_report.md
          echo "" >> api_report.md
          echo "| Check | Status | HTTP Code | Time |" >> api_report.md
          echo "| :--- | :--- | :--- | :--- |" >> api_report.md
          echo "| **Login Endpoint** | $status_icon **$status_msg** | \`$http_code\` | $(date +'%H:%M:%S') |" >> api_report.md
          echo "" >> api_report.md

      - name: Init Graph Repository
        id: graph_step
        if: env.ACCESS_TOKEN != '' 
        env:
          GRAPH_URL: https://tasimetric-willard-noncosmic.ngrok-free.dev/graph/init
          REPO_OWNER: ${{ secrets.REPOSITORY_OWNER }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          GRAPH_BODY="{\"owner\":\"$REPO_OWNER\", \"name\":\"$REPO_NAME\", \"user_id\":\"$USER_ID\"}"

          response=$(curl -s -w "\n%{http_code}" -X POST "$GRAPH_URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -d "$GRAPH_BODY")

          code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)

          if [ "$code" == "200" ] || [ "$code" == "201" ]; then
             icon="🟢"
             msg="Initialized"
          else
             icon="🔴"
             msg="Error"
          fi

          echo "| **2. Graph Init** | $icon **$msg** | \`$code\` | Repo: \`$REPO_NAME\` |" >> api_report.md

          echo "" >> api_report.md

      - name: Post API Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: api-check-report 
          path: api_report.md